### ISSUE TITLE
Can You please help me in setting up this project after cloning...

### ISSUE THREAD

**Issue by bitaashna** [muzam1l/mooz#3]
I am facing some issues after downloading the project. That's why unable to setup it. Please guide me through this

**Comment by muzam1l** [comment]
Hi bitaashna
So there are two ways to run the project, Docker and or manually with npm. Basically, it is split between React front-end and Node server. Can you describe what are the issues you are facing, would love to help.

**Comment by bitaashna** [comment]
![package-lock json - mooz - Visual Studio Code 08-07-2021 16_24_47](https://user-images.githubusercontent.com/57864526/124958666-04bb8a80-dfe0-11eb-94b1-40390918e601.png)
![package-lock json - mooz - Visual Studio Code 08-07-2021 16_25_00](https://user-images.githubusercontent.com/57864526/124958702-10a74c80-dfe0-11eb-8059-3d1d2eecfc3b.png)
![package-lock json - mooz - Visual Studio Code 08-07-2021 16_25_07](https://user-images.githubusercontent.com/57864526/124958745-1d2ba500-dfe0-11eb-87af-191c61b9afd8.png)
![package-lock json - mooz - Visual Studio Code 08-07-2021 16_25_18](https://user-images.githubusercontent.com/57864526/124958761-20269580-dfe0-11eb-9bb7-443debe84945.png)
![package-lock json - mooz - Visual Studio Code 08-07-2021 16_25_28](https://user-images.githubusercontent.com/57864526/124958772-23218600-dfe0-11eb-9441-fc1b47687a6d.png)
![package-lock json - mooz - Visual Studio Code 08-07-2021 16_25_39](https://user-images.githubusercontent.com/57864526/124958777-2583e000-dfe0-11eb-9c75-5ba6002aa137.png)
![package-lock json - mooz - Visual Studio Code 08-07-2021 16_25_48](https://user-images.githubusercontent.com/57864526/124958783-27e63a00-dfe0-11eb-895e-83d629fae34d.png)
![package-lock json - mooz - Visual Studio Code 08-07-2021 16_26_05](https://user-images.githubusercontent.com/57864526/124958786-2a489400-dfe0-11eb-92c0-6400a716c62c.png)

why am i getting the above vulnerabilities.Can u please guide me to proceed further..

**Comment by muzam1l** [comment]
These are the vulnerabilities of different levels in `npm` modules. Most of those modules are not our direct dependencies, so it's best to leave it until our direct dependency module fixes it themselves. You will always have some of them in your code and many of the times they do not affect the project at all. The ones which are not fixed by `npm audit fix` are usually the breaking change upgrades, therefore you must check module's release notes, you upgrade, for any breaking changes.

If it's all overwhelming for you, don't worry and leave it, just keep your fork updated with this repo and I will fix them if needed from time to time.

**Comment by bitaashna** [comment]
okay..
![package-lock json - mooz - Visual Studio Code 08-07-2021 17_13_51](https://user-images.githubusercontent.com/57864526/124964064-2ddf1980-dfe6-11eb-9494-e2006121f4b2.png)
![mooz - Google Chrome 08-07-2021 17_15_56](https://user-images.githubusercontent.com/57864526/124964185-5404b980-dfe6-11eb-8d09-8ab1a3602eaf.png)
how to fix it?

**Comment by muzam1l** [comment]
That's AFTER you made edits, right? Then It's what it says, you have already declared this variable before this line.

**Comment by bitaashna** [comment]
nope, i haven't editted, just running the manual commands and its showing this error

**Comment by muzam1l** [comment]
Well that's strange, just checked it compiles just fine, are you sure there are no edits, including any package upgrade? Check git chnages to be sure.

**Comment by bitaashna** [comment]
ok got it..
on running npm run dev getting this... what should i do?
> mooz@1.0.0 dev
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.

**Comment by muzam1l** [comment]
That just means react-scripts is not installed, it's in package.json it should have been installed on `npm install`. So did you uninstalled that? run `npm install again maybe

**Comment by bitaashna** [comment]
on running npm install below error is there

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: typescript@4.1.3
npm ERR! node_modules/typescript
npm ERR!   dev typescript@"^4.1.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^3.2.1" from react-scripts@4.0.1
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"4.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by muzam1l** [comment]
Well that again is the issue you are having, is not related to this project, and requires manual review. What I may suggest is first see if you have latest npm, etc and then start over, delete `node_modules`, discard all changes, ensure the latest commit is fetched `git pull` and then try again with `npm install`.
